fieldLayouts:
  8bdda6b6-d7ad-4ab0-a3a3-74fa934aa592:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1b19e1c6-6810-4c10-8bb8-b9616915567b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b46261e-0e57-494a-866a-592a7e19c11d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e41c5ce7-a865-475b-bb2f-76fbcc994348
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e597fe0-9333-41f1-bb67-3cd9d5461a56
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f686ef31-94e0-4c16-a372-ac5ea4f7e163 # Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
