defaultPlacement: end
enableVersioning: false
handle: navigation
name: Navigation
propagationMethod: all
siteSettings:
  fe9a96dd-f659-48a1-9d2c-a7e9df599648: # telcopoints
    enabledByDefault: true
    hasUrls: true
    template: navigation/_entry
    uriFormat: navigation
type: single
